### ISSUE TITLE
Dataset license violation

### ISSUE THREAD

**Issue by sergiud** [tayebiarasteh/PV_defect_detection#4]
Hi,

You have taken the [images](https://github.com/tayebiarasteh/PV_defect_detection/tree/master/data/images) from our [EL PV dataset](https://github.com/zae-bayern/elpv-dataset) while disregarding the license (cf. [our images](https://github.com/zae-bayern/elpv-dataset/tree/master/images).) In particular, your repository implies that the data is provided under the MIT license and you own the copyright which is not the case.

To avoid a takedown of your repository, please ensure to follow the [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license by
1. Updating the README to reference the source and the license. The license text must be provided along the data. (Attribution)
2. Provide your contributions to the dataset under the same license (ShareAlike)

Please also make sure to respect the license and any intellectual property in the future.

Thank you.

**Comment by tayebiarasteh** [comment]
Hi, Thank you for your message, and apologies for the misunderstanding. The dataset attributions are updated as you requested. The license of the repo corresponded to the method and not the dataset.
